json: true
log: experiment_results/trt_results_patches20_tmp0.7_topp0.95_gpt-3.5-turbo/unchecked_low_level_calls/analyzers_natural_language_results/0x5aa88d2901c68fda244f1d0584400368d2c8e739/candidate_patches/patch_10/smartbugs_logs/{RUNID}.log
processes: 11
results: experiment_results/trt_results_patches20_tmp0.7_topp0.95_gpt-3.5-turbo/unchecked_low_level_calls/analyzers_natural_language_results/0x5aa88d2901c68fda244f1d0584400368d2c8e739/candidate_patches/patch_10/smartbugs_results/${TOOL}_${RUNID}
runid: ${YEAR}${MONTH}${DAY}_${HOUR}${MIN}
runtime: false
timeout: 3600
tools:
- smartcheck
- mythril
- manticore
- securify
