json: true
log: /Users/erikcruz/Documents/thesis_repos/transformative_smart_contract_repair/experiment_results/smartbugs_reentrancy_short_no_comments_tools3_patches10_tmp0.7_topp0.95_gpt-3.5-turbo/analyzers_json_results/0x7541b76cb60f4c60af330c208b0623b7f54bf615/candidate_patches/patch_8/smartbugs_logs/{RUNID}.log
processes: 11
results: /Users/erikcruz/Documents/thesis_repos/transformative_smart_contract_repair/experiment_results/smartbugs_reentrancy_short_no_comments_tools3_patches10_tmp0.7_topp0.95_gpt-3.5-turbo/analyzers_json_results/0x7541b76cb60f4c60af330c208b0623b7f54bf615/candidate_patches/patch_8/smartbugs_results/${TOOL}_${RUNID}
runid: ${YEAR}${MONTH}${DAY}_${HOUR}${MIN}
runtime: false
timeout: 420
tools:
- oyente
- slither
- osiris
