json: true
log: /Users/erikcruz/Documents/thesis_repos/transformative_smart_contract_repair/experiment_results/smartbugs_reentrancy_short_no_comments_tools3_patches10_tmp0.7_topp0.95_gpt-3.5-turbo/analyzers_json_results/0xbe4041d55db380c5ae9d4a9b9703f1ed4e7e3888/smartbugs_logs/{RUNID}.log
processes: 11
results: /Users/erikcruz/Documents/thesis_repos/transformative_smart_contract_repair/experiment_results/smartbugs_reentrancy_short_no_comments_tools3_patches10_tmp0.7_topp0.95_gpt-3.5-turbo/analyzers_json_results/0xbe4041d55db380c5ae9d4a9b9703f1ed4e7e3888/smartbugs_results/${TOOL}_${RUNID}
runid: ${YEAR}${MONTH}${DAY}_${HOUR}${MIN}
runtime: false
timeout: 420
tools:
- oyente
- slither
- osiris
