# Configuration file for automatic program repair experiments

# Folder name for results
experiment_settings:
  experiment_name: "<experiment_name>"
  delete_old_experiment_name: <delete_old_experiment_name> # true or false
  llm_model_name: "<llm_model_name>"
  vulnerable_contracts_directory: "<vulnerable_contracts_directory>"
  target_vulnerabilities: [<target_vulnerabilities>] # [access_control, arithmetic, transaction_order_dependence, reentrancy, unchecked_low_level_call, unhandled_exception]
  n_smartbugs_threads: <n_smartbugs_threads>
  n_repair_threads: <n_repair_threads>
  smartbugs_tools: [<smartbugs_tools>]
  smartbugs_timeout: <smartbugs_timeout>
  smartbugs_processes: <smartbugs_processes>
  patch_examples_directory: "<patch_examples_directory>"
  prompt_style: "<prompt_style>" # Alternatives: "basic", "analyzers_json_results", "analyzers_natural_language_results"

# LLM model and settings
llm_settings:
  <llm_model_name>:
    model_name: "<llm_model_name>"
    secret_api_key: "<secret_api_key>"
    temperature: <temperature>
    top_p: <top_p>
    num_candidate_patches: <num_candidate_patches>
    max_time: <max_time>
    stop: ["///"]