# Configuration file for automatic program repair experiments

# Folder name for results
experiment_settings:
  experiment_name: "test-experiment"
  delete_old_experiment_name: true
  llm_model: "gpt-3.5-turbo"
  vulnerable_contracts_directory: "sc_to_repair" # Folder name for buggy smart contracts
  target_vulnerabilities: [reentrancy]
  n_smartbugs_threads: 10
  n_repair_threads: 10
  smartbugs_tools: [oyente]
  patch_examples_directory: "sc_repair_examples"
  #prompt_style: "C_vulnerability_examples"
  prompt_style: "A_basic"

# LLM model and settings
llm_settings:
  gpt-3.5-turbo:
    model_name: "gpt-3.5-turbo"
    secret_api_key: "OPENAI_API_KEY"
    temperature: 0.5
    top_p: 0.9
    num_candidate_patches: 1
    max_time: 3600
    stop: ["///"]
