#files: [/Users/erik/Documents/repositories_thesis/transformative_smart_contract_repair/sc_datasets/smartbugs_curated/reentrancy/test.sol]
runtime: false
#tools: [oyente, mythril, slither]
tools: [oyente, slither]
runid: ${YEAR}${MONTH}${DAY}_${HOUR}${MIN}
##   vars: YEAR, MONTH, DAY, HOUR, MIN, SEC, ZONE,
##   HOME, PID, SBVERSION, SBHOME
#overwrite: false
#processes: 1
#timeout: 0 # [s] 0/null = no timeout
#cpu-quota: 0 # 0/null = no quota
#mem-limit: 0 # "512m" or "4g"  0/null = no quota
results: sb_results/${FILENAME}/${TOOL}_${RUNID}
##   vars: all vars from "runid" above, as well as RUNID,
##   TOOL, MODE (solidity, bytecode, runtime), ABSDIR, RELDIR,
##   FILENAME, FILEBASE, FILEEXT (FILENAME = FILEBASE + "." + FILEEXT)
log: sb_results/logs/${RUNID}.log
##   vars: all vars from "runid" above, as well as RUNID
json: true
#sarif: false
#quiet: false


runtime: false
tools: [oyente, slither]
runid: ${YEAR}${MONTH}${DAY}_${HOUR}${MIN}
results: sb_results/${FILENAME}/${TOOL}_${RUNID}
log: sb_results/logs/${RUNID}.log
json: true