json: true
log: /Users/erikcruz/Documents/thesis_repos/transformative_smart_contract_repair/experiment_results/test_gpt-3.5-turbo/0xf015c35649c82f5467c9c74b7f28ee67665aad68/candidate_patches/patch_1/smartbugs_logs/{RUNID}.log
results: /Users/erikcruz/Documents/thesis_repos/transformative_smart_contract_repair/experiment_results/test_gpt-3.5-turbo/0xf015c35649c82f5467c9c74b7f28ee67665aad68/candidate_patches/patch_1/smartbugs_results/${TOOL}_${RUNID}
runid: ${YEAR}${MONTH}${DAY}_${HOUR}${MIN}
runtime: false
tools:
- oyente
- slither
