name: HoneyBadger
version: "#ff30c9a"
info: An analysis tool to detect honeypots in Ethereum smart contracts
origin: https://github.com/christoftorres/HoneyBadger
image: smartbugs/honeybadger:ff30c9a
bin: scripts
solidity:
    entrypoint: "'$BIN/do_solidity.sh' '$FILENAME' '$TIMEOUT' '$BIN' '$MAIN'"
    solc: yes
runtime:
    entrypoint: "'$BIN/do_runtime.sh' '$FILENAME' '$TIMEOUT'"
