json: true
log: experiment_results/1-project-two-simple-projects_patches10_tmp0.9_topp0.3_gpt-3.5-turbo/code/smartbugs_logs/{RUNID}.log
processes: 11
results: experiment_results/1-project-two-simple-projects_patches10_tmp0.9_topp0.3_gpt-3.5-turbo/code/smartbugs_results/${TOOL}_${RUNID}
runid: ${YEAR}${MONTH}${DAY}_${HOUR}${MIN}
runtime: false
timeout: 3600
tools:
- semgrep
- smartcheck
- slither
