json: true
log: /Users/erikcruz/Documents/thesis_repos/transformative_smart_contract_repair/experiment_results/prompt_comparison_reentrancy_tools3_patches10_tmp0.7_topp0.95_gpt-3.5-turbo/basic/0xaae1f51cf3339f18b6d3f3bdc75a5facd744b0b8/candidate_patches/patch_0/smartbugs_logs/{RUNID}.log
processes: 11
results: /Users/erikcruz/Documents/thesis_repos/transformative_smart_contract_repair/experiment_results/prompt_comparison_reentrancy_tools3_patches10_tmp0.7_topp0.95_gpt-3.5-turbo/basic/0xaae1f51cf3339f18b6d3f3bdc75a5facd744b0b8/candidate_patches/patch_0/smartbugs_results/${TOOL}_${RUNID}
runid: ${YEAR}${MONTH}${DAY}_${HOUR}${MIN}
runtime: false
timeout: 180
tools:
- mythril
- oyente
- slither
