json: true
log: /Users/erikcruz/Documents/thesis_repos/transformative_smart_contract_repair/experiment_results/smartbugs_reentrancy_short_10_patches_4_tools_gpt-3.5-turbo/0xaae1f51cf3339f18b6d3f3bdc75a5facd744b0b8/candidate_patches/patch_6/smartbugs_logs/{RUNID}.log
processes: 11
results: /Users/erikcruz/Documents/thesis_repos/transformative_smart_contract_repair/experiment_results/smartbugs_reentrancy_short_10_patches_4_tools_gpt-3.5-turbo/0xaae1f51cf3339f18b6d3f3bdc75a5facd744b0b8/candidate_patches/patch_6/smartbugs_results/${TOOL}_${RUNID}
runid: ${YEAR}${MONTH}${DAY}_${HOUR}${MIN}
runtime: false
timeout: 180
tools:
- oyente
- slither
- honeybadger
- osiris
