json: true
log: /Users/erikcruz/Documents/thesis_repos/transformative_smart_contract_repair/experiment_results/test_gpt-3.5-turbo/0xbe4041d55db380c5ae9d4a9b9703f1ed4e7e3888/candidate_patches/patch_1/smartbugs_logs/{RUNID}.log
results: /Users/erikcruz/Documents/thesis_repos/transformative_smart_contract_repair/experiment_results/test_gpt-3.5-turbo/0xbe4041d55db380c5ae9d4a9b9703f1ed4e7e3888/candidate_patches/patch_1/smartbugs_results/${TOOL}_${RUNID}
runid: ${YEAR}${MONTH}${DAY}_${HOUR}${MIN}
runtime: false
tools:
- oyente
- slither
