json: true
log: /Users/erikcruz/Documents/thesis_repos/transformative_smart_contract_repair/experiment_results/test_gpt-3.5-turbo/etherbank/smartbugs_logs/{RUNID}.log
results: /Users/erikcruz/Documents/thesis_repos/transformative_smart_contract_repair/experiment_results/test_gpt-3.5-turbo/etherbank/smartbugs_results/${TOOL}_${RUNID}
runid: ${YEAR}${MONTH}${DAY}_${HOUR}${MIN}
runtime: false
tools:
- oyente
- slither
