json: true
log: experiment_results/DAppSCAN_first_experiment_patches20_tmp0.7_topp0.95_gpt-3.5-turbo/SimpleMultiSig/candidate_patches/patch_19/smartbugs_logs/{RUNID}.log
processes: 11
results: experiment_results/DAppSCAN_first_experiment_patches20_tmp0.7_topp0.95_gpt-3.5-turbo/SimpleMultiSig/candidate_patches/patch_19/smartbugs_results/${TOOL}_${RUNID}
runid: ${YEAR}${MONTH}${DAY}_${HOUR}${MIN}
runtime: false
timeout: 3600
tools:
- mythril
