json: true
log: /Users/erikcruz/Documents/thesis_repos/transformative_smart_contract_repair/experiment_results/smartbugs_reentrancy_short_10_patches_4_tools_gpt-3.5-turbo/reentrancy_cross_function/candidate_patches/patch_3/smartbugs_logs/{RUNID}.log
processes: 11
results: /Users/erikcruz/Documents/thesis_repos/transformative_smart_contract_repair/experiment_results/smartbugs_reentrancy_short_10_patches_4_tools_gpt-3.5-turbo/reentrancy_cross_function/candidate_patches/patch_3/smartbugs_results/${TOOL}_${RUNID}
runid: ${YEAR}${MONTH}${DAY}_${HOUR}${MIN}
runtime: false
tools:
- oyente
- slither
- honeybadger
- osiris
