json: true
log: /Users/erikcruz/Documents/thesis_repos/transformative_smart_contract_repair/experiment_results/smartbugs_reentrancy_short_no_comments_tools3_patches10_tmp0.5_topp0.95_gpt-3.5-turbo/analyzers_natural_language_results/0x93c32845fae42c83a70e5f06214c8433665c2ab5/candidate_patches/patch_6/smartbugs_logs/{RUNID}.log
processes: 11
results: /Users/erikcruz/Documents/thesis_repos/transformative_smart_contract_repair/experiment_results/smartbugs_reentrancy_short_no_comments_tools3_patches10_tmp0.5_topp0.95_gpt-3.5-turbo/analyzers_natural_language_results/0x93c32845fae42c83a70e5f06214c8433665c2ab5/candidate_patches/patch_6/smartbugs_results/${TOOL}_${RUNID}
runid: ${YEAR}${MONTH}${DAY}_${HOUR}${MIN}
runtime: false
timeout: 420
tools:
- oyente
- slither
- osiris
