json: true
log: experiment_results/sbc_no_comment_1h_tools3_patches20_tmp0.7_topp0.95_gpt-3.5-turbo/reentrancy/analyzers_natural_language_results/0x93c32845fae42c83a70e5f06214c8433665c2ab5/candidate_patches/patch_6/smartbugs_logs/{RUNID}.log
processes: 11
results: experiment_results/sbc_no_comment_1h_tools3_patches20_tmp0.7_topp0.95_gpt-3.5-turbo/reentrancy/analyzers_natural_language_results/0x93c32845fae42c83a70e5f06214c8433665c2ab5/candidate_patches/patch_6/smartbugs_results/${TOOL}_${RUNID}
runid: ${YEAR}${MONTH}${DAY}_${HOUR}${MIN}
runtime: false
timeout: 3600
tools:
- mythril
- oyente
- slither
