json: true
log: experiment_results/trt_results_prompt_comparison_patches20_tmp0.7_topp0.95_gpt-3.5-turbo/reentrancy/analyzers_natural_language_results/0x7b368c4e805c3870b6c49a3f1f49f69af8662cf3/candidate_patches/patch_0/smartbugs_logs/{RUNID}.log
processes: 11
results: experiment_results/trt_results_prompt_comparison_patches20_tmp0.7_topp0.95_gpt-3.5-turbo/reentrancy/analyzers_natural_language_results/0x7b368c4e805c3870b6c49a3f1f49f69af8662cf3/candidate_patches/patch_0/smartbugs_results/${TOOL}_${RUNID}
runid: ${YEAR}${MONTH}${DAY}_${HOUR}${MIN}
runtime: false
timeout: 3600
tools:
- slither
- oyente
- securify
