json: true
log: experiment_results/trt_results_prompt_comparison_patches20_tmp0.7_topp0.95_gpt-3.5-turbo/reentrancy/analyzers_json_results/0xbe4041d55db380c5ae9d4a9b9703f1ed4e7e3888/candidate_patches/patch_16/smartbugs_logs/{RUNID}.log
processes: 11
results: experiment_results/trt_results_prompt_comparison_patches20_tmp0.7_topp0.95_gpt-3.5-turbo/reentrancy/analyzers_json_results/0xbe4041d55db380c5ae9d4a9b9703f1ed4e7e3888/candidate_patches/patch_16/smartbugs_results/${TOOL}_${RUNID}
runid: ${YEAR}${MONTH}${DAY}_${HOUR}${MIN}
runtime: false
timeout: 3600
tools:
- oyente
- securify
- slither
