json: true
log: /Users/erikcruz/Documents/thesis_repos/transformative_smart_contract_repair/experiment_results/prompt_comparison_reentrancy_tools3_patches10_tmp0.7_topp0.95_gpt-3.5-turbo/basic/0x7b368c4e805c3870b6c49a3f1f49f69af8662cf3/candidate_patches/patch_8/smartbugs_logs/{RUNID}.log
processes: 11
results: /Users/erikcruz/Documents/thesis_repos/transformative_smart_contract_repair/experiment_results/prompt_comparison_reentrancy_tools3_patches10_tmp0.7_topp0.95_gpt-3.5-turbo/basic/0x7b368c4e805c3870b6c49a3f1f49f69af8662cf3/candidate_patches/patch_8/smartbugs_results/${TOOL}_${RUNID}
runid: ${YEAR}${MONTH}${DAY}_${HOUR}${MIN}
runtime: false
timeout: 180
tools:
- mythril
- oyente
- slither
