json: true
log: experiment_results/sbc_no_comment_1h_tools3_patches20_tmp0.7_topp0.95_gpt-3.5-turbo/unchecked_low_level_call/analyzers_natural_language_results/0xbebbfe5b549f5db6e6c78ca97cac19d1fb03082c/smartbugs_logs/{RUNID}.log
processes: 11
results: experiment_results/sbc_no_comment_1h_tools3_patches20_tmp0.7_topp0.95_gpt-3.5-turbo/unchecked_low_level_call/analyzers_natural_language_results/0xbebbfe5b549f5db6e6c78ca97cac19d1fb03082c/smartbugs_results/${TOOL}_${RUNID}
runid: ${YEAR}${MONTH}${DAY}_${HOUR}${MIN}
runtime: false
timeout: 3600
tools:
- mythril
- oyente
- slither
