json: true
log: /Users/erikcruz/Documents/thesis_repos/transformative_smart_contract_repair/experiment_results/test_gpt-3.5-turbo/0xcead721ef5b11f1a7b530171aab69b16c5e66b6e/smartbugs_logs/{RUNID}.log
results: /Users/erikcruz/Documents/thesis_repos/transformative_smart_contract_repair/experiment_results/test_gpt-3.5-turbo/0xcead721ef5b11f1a7b530171aab69b16c5e66b6e/smartbugs_results/${TOOL}_${RUNID}
runid: ${YEAR}${MONTH}${DAY}_${HOUR}${MIN}
runtime: false
tools:
- oyente
- slither
