json: true
log: experiment_results/sbc_no_comment_1h_tools3_patches20_tmp0.7_topp0.95_gpt-3.5-turbo/unchecked_low_level_call/analyzers_natural_language_results/0x9d06cbafa865037a01d322d3f4222fa3e04e5488/candidate_patches/patch_19/smartbugs_logs/{RUNID}.log
processes: 11
results: experiment_results/sbc_no_comment_1h_tools3_patches20_tmp0.7_topp0.95_gpt-3.5-turbo/unchecked_low_level_call/analyzers_natural_language_results/0x9d06cbafa865037a01d322d3f4222fa3e04e5488/candidate_patches/patch_19/smartbugs_results/${TOOL}_${RUNID}
runid: ${YEAR}${MONTH}${DAY}_${HOUR}${MIN}
runtime: false
timeout: 3600
tools:
- mythril
- oyente
- slither
