json: true
log: /Users/erikcruz/Documents/thesis_repos/transformative_smart_contract_repair/experiment_results/sbc_no_comment_tools3_patches20_tmp0.7_topp0.95_gpt-3.5-turbo/reentrancy/analyzers_json_results/0xaae1f51cf3339f18b6d3f3bdc75a5facd744b0b8/candidate_patches/patch_5/smartbugs_logs/{RUNID}.log
processes: 11
results: /Users/erikcruz/Documents/thesis_repos/transformative_smart_contract_repair/experiment_results/sbc_no_comment_tools3_patches20_tmp0.7_topp0.95_gpt-3.5-turbo/reentrancy/analyzers_json_results/0xaae1f51cf3339f18b6d3f3bdc75a5facd744b0b8/candidate_patches/patch_5/smartbugs_results/${TOOL}_${RUNID}
runid: ${YEAR}${MONTH}${DAY}_${HOUR}${MIN}
runtime: false
timeout: 180
tools:
- mythril
- oyente
- slither
