json: true
log: experiment_results/DAppSCAN_second_experiment/TestRegistry/smartbugs_logs/{RUNID}.log
processes: 11
results: experiment_results/DAppSCAN_second_experiment/TestRegistry/smartbugs_results/${TOOL}_${RUNID}
runid: ${YEAR}${MONTH}${DAY}_${HOUR}${MIN}
runtime: false
timeout: 3600
tools:
- manticore
- oyente
- osiris
- smartcheck
- mythril
