json: true
log: /Users/erikcruz/Documents/thesis_repos/transformative_smart_contract_repair/experiment_results/prompt_comparison_reentrancy_tools3_patches10_tmp0.7_topp0.95_gpt-3.5-turbo/basic/0x561eac93c92360949ab1f1403323e6db345cbf31/smartbugs_logs/{RUNID}.log
processes: 11
results: /Users/erikcruz/Documents/thesis_repos/transformative_smart_contract_repair/experiment_results/prompt_comparison_reentrancy_tools3_patches10_tmp0.7_topp0.95_gpt-3.5-turbo/basic/0x561eac93c92360949ab1f1403323e6db345cbf31/smartbugs_results/${TOOL}_${RUNID}
runid: ${YEAR}${MONTH}${DAY}_${HOUR}${MIN}
runtime: false
timeout: 1200
tools:
- mythril
- oyente
- slither
