json: true
log: experiment_results/trt_results_patches20_tmp0.7_topp0.95_gpt-3.5-turbo/reentrancy/analyzers_natural_language_results/0x23a91059fdc9579a9fbd0edc5f2ea0bfdb70deb4/candidate_patches/patch_13/smartbugs_logs/{RUNID}.log
processes: 11
results: experiment_results/trt_results_patches20_tmp0.7_topp0.95_gpt-3.5-turbo/reentrancy/analyzers_natural_language_results/0x23a91059fdc9579a9fbd0edc5f2ea0bfdb70deb4/candidate_patches/patch_13/smartbugs_results/${TOOL}_${RUNID}
runid: ${YEAR}${MONTH}${DAY}_${HOUR}${MIN}
runtime: false
timeout: 3600
tools:
- slither
- mythril
- manticore
- securify
- oyente
