json: true
log: experiment_results/reentrancy-attacks_patches20_tmp0.7_topp0.95_gpt-3.5-turbo/Akropolis/smartbugs_logs/{RUNID}.log
processes: 11
results: experiment_results/reentrancy-attacks_patches20_tmp0.7_topp0.95_gpt-3.5-turbo/Akropolis/smartbugs_results/${TOOL}_${RUNID}
runid: ${YEAR}${MONTH}${DAY}_${HOUR}${MIN}
runtime: false
timeout: 3600
tools:
- slither
- smartcheck
