json: true
log: /Users/erikcruz/Documents/thesis_repos/transformative_smart_contract_repair/experiment_results/prompt_comparison_reentrancy_tools3_patches10_tmp0.7_topp0.95_gpt-3.5-turbo/analyzers_json_results/0xb93430ce38ac4a6bb47fb1fc085ea669353fd89e/candidate_patches/patch_8/smartbugs_logs/{RUNID}.log
processes: 11
results: /Users/erikcruz/Documents/thesis_repos/transformative_smart_contract_repair/experiment_results/prompt_comparison_reentrancy_tools3_patches10_tmp0.7_topp0.95_gpt-3.5-turbo/analyzers_json_results/0xb93430ce38ac4a6bb47fb1fc085ea669353fd89e/candidate_patches/patch_8/smartbugs_results/${TOOL}_${RUNID}
runid: ${YEAR}${MONTH}${DAY}_${HOUR}${MIN}
runtime: false
timeout: 180
tools:
- mythril
- oyente
- slither
