json: true
log: experiment_results/trt_results_patches20_tmp0.7_topp0.95_gpt-3.5-turbo/unchecked_low_level_calls/analyzers_natural_language_results/0x610495793564aed0f9c7fc48dc4c7c9151d34fd6/candidate_patches/patch_0/smartbugs_logs/{RUNID}.log
processes: 11
results: experiment_results/trt_results_patches20_tmp0.7_topp0.95_gpt-3.5-turbo/unchecked_low_level_calls/analyzers_natural_language_results/0x610495793564aed0f9c7fc48dc4c7c9151d34fd6/candidate_patches/patch_0/smartbugs_results/${TOOL}_${RUNID}
runid: ${YEAR}${MONTH}${DAY}_${HOUR}${MIN}
runtime: false
timeout: 3600
tools:
- smartcheck
- mythril
- manticore
- securify
