json: true
log: experiment_results/test-experiment_gpt-3.5-turbo/reentrance/smartbugs_logs/{RUNID}.log
results: experiment_results/test-experiment_gpt-3.5-turbo/reentrance/smartbugs_results/${TOOL}_${RUNID}
runid: ${YEAR}${MONTH}${DAY}_${HOUR}${MIN}
runtime: false
tools:
- oyente
