json: true
log: experiment_results/trt_results_prompt_comparison_patches20_tmp0.7_topp0.95_gpt-3.5-turbo/reentrancy/analyzers_natural_language_results/0x941d225236464a25eb18076df7da6a91d0f95e9e/candidate_patches/patch_0/smartbugs_logs/{RUNID}.log
processes: 11
results: experiment_results/trt_results_prompt_comparison_patches20_tmp0.7_topp0.95_gpt-3.5-turbo/reentrancy/analyzers_natural_language_results/0x941d225236464a25eb18076df7da6a91d0f95e9e/candidate_patches/patch_0/smartbugs_results/${TOOL}_${RUNID}
runid: ${YEAR}${MONTH}${DAY}_${HOUR}${MIN}
runtime: false
timeout: 3600
tools:
- securify
- slither
- oyente
