json: true
log: experiment_results/trt_results_prompt_comparison_patches20_tmp0.7_topp0.95_gpt-3.5-turbo/reentrancy/analyzers_json_results/0x01f8c4e3fa3edeb29e514cba738d87ce8c091d3f/candidate_patches/patch_18/smartbugs_logs/{RUNID}.log
processes: 11
results: experiment_results/trt_results_prompt_comparison_patches20_tmp0.7_topp0.95_gpt-3.5-turbo/reentrancy/analyzers_json_results/0x01f8c4e3fa3edeb29e514cba738d87ce8c091d3f/candidate_patches/patch_18/smartbugs_results/${TOOL}_${RUNID}
runid: ${YEAR}${MONTH}${DAY}_${HOUR}${MIN}
runtime: false
timeout: 3600
tools:
- oyente
- securify
- slither
