json: true
log: experiment_results/sbc_no_comment_1h_tools3_patches20_tmp0.7_topp0.95_gpt-3.5-turbo/unchecked_low_level_call/analyzers_natural_language_results/0x3f2ef511aa6e75231e4deafc7a3d2ecab3741de2/candidate_patches/patch_6/smartbugs_logs/{RUNID}.log
processes: 11
results: experiment_results/sbc_no_comment_1h_tools3_patches20_tmp0.7_topp0.95_gpt-3.5-turbo/unchecked_low_level_call/analyzers_natural_language_results/0x3f2ef511aa6e75231e4deafc7a3d2ecab3741de2/candidate_patches/patch_6/smartbugs_results/${TOOL}_${RUNID}
runid: ${YEAR}${MONTH}${DAY}_${HOUR}${MIN}
runtime: false
timeout: 3600
tools:
- mythril
- oyente
- slither
