json: true
log: experiment_results/sbc_no_comment_1h_tools3_patches20_tmp0.7_topp0.95_gpt-3.5-turbo/arithmetic/analyzers_natural_language_results/integer_overflow_multitx_multifunc_feasible/candidate_patches/patch_16/smartbugs_logs/{RUNID}.log
processes: 11
results: experiment_results/sbc_no_comment_1h_tools3_patches20_tmp0.7_topp0.95_gpt-3.5-turbo/arithmetic/analyzers_natural_language_results/integer_overflow_multitx_multifunc_feasible/candidate_patches/patch_16/smartbugs_results/${TOOL}_${RUNID}
runid: ${YEAR}${MONTH}${DAY}_${HOUR}${MIN}
runtime: false
timeout: 3600
tools:
- mythril
- oyente
- slither
